[project]
name = "langchain-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zenith-11", email = "samalabhinash351@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
langchain-app = "langchain_app:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
